name: obe-prod

services:

  obe-prod-app:
    container_name: obe-prod-app
    image: obe:1.01
    ports:
      - "8091:80"
    networks:
      -  obe-prod-network
    environment:
      - DB_HOST=host.docker.internal:33062
      - DB_USER=root
      - DB_PWD=actando
      - DB_NAME=obe
      - APP_URL=localhost:8091
      - EMAIL_FROM=conctact@obe28.com
      - ACTIVATE_EMAIL=false

networks:
  obe-prod-network:
    name: obe-prod-network
    driver: bridge