server {

  listen 80 default_server;
  listen [::]:80 default_server;

  root /var/www/app;

  # Add index.php to setup Nginx, PHP & PHP-FPM config
  index index.php index.html index.htm index.nginx-debian.html;

  server_name _;

  location / {
    try_files $uri $uri/ =404;
  }

# pass PHP scripts on Nginx to FastCGI (PHP-FPM) server
  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php8.2-fpm.sock;
  }

  # deny access to Apache .htaccess on Nginx with PHP, 
  # if Apache and Nginx document roots concur
  location ~ /\.ht {
    deny all;
  }

}

server {

    listen 8000;
 
    index index.php;

    charset utf-8;

    root /var/www/app;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }

    location / {
      try_files $uri $uri/ =404;
      gzip_static on;
    }

    # deny access to Apache .htaccess on Nginx with PHP, 
    # if Apache and Nginx document roots concur
    location ~ /\.ht {
      deny all;
    }

}